#!/bin/sh
cd ~
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export QT_SCALE_FACTOR=1
#export GBM_BACKEND=nvidia-drm
#export LIBVA_DRIVER_NAME=nvidia
#export __GLX_VENDOR_LIBRARY_NAME=nvidia
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland 
export WLR_NO_HARDWARE_CURSORS=1

#export XCURSOR_THEME=Adwaita-cursors

#export XCURSOR_SIZE=24

someblocks -p | dwlb -status-stdin all &
gentoo-pipewire-launcher &
#dwlb -font "JetBrainsMonoNerdFontMono:size=12"
#foot --server <&-
#dwl
exec dbus-launch --exit-with-session dwl -s 'dwlb -font "JetBrainsMonoNerdFontMono:size=10"'

#wlr-randr --output DP-2 --mode 2560x1440@165Hz
#wlr-randr --output DP-3 --mode 2560x1440@239.998001Hz
