#!/bin/sh
cd ~
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export QT_SCALE_FACTOR=1
export GBM_BACKEND=nvidia-drm
export LIBVA_DRIVER_NAME=nvidia
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland 
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=wlr
export XDG_SESSION_DESKTOP=wlr
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
#FOR VM TESTING ONLY vvv
#export WLR_RENDERER_ALLOW_SOFTWARE=1
export EDITOR=nvim

export BEMENU_OPTS="
    --ignorecase\
    --prompt ''\
    --fn 'JetBrainsMono NerdFont 10'\
    --ch '20'\
    --center\
    --width-factor '0.25'\
    --list '14'\
    --line-height '26'\
    --fixed-height\
    --border '2'\
    --bdr '#c0caf5'\
    --hb '#292e42' --hf '#c0caf5'\
    --nb '#1a1b26' --nf '#a9b1d6'\
    --ab '#1a1b26' --af '#a9b1d6'\
    --fb '#1a1b26' --ff '#a9b1d6'\
"

someblocks & 
exec dbus-launch --exit-with-session dwl -s 'somebar'

