#!/bin/sh
cd ~
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export QT_SCALE_FACTOR=1
#export GBM_BACKEND=nvidia-drm
#export LIBVA_DRIVER_NAME=nvidia
#export __GLX_VENDOR_LIBRARY_NAME=nvidia
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland 
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=wlr

#FOR VM TESTING ONLY vvv
#export WLR_RENDERER_ALLOW_SOFTWARE=1

someblocks -p | dwlb -status-stdin all &
exec dbus-launch --exit-with-session dwl -s 'dwlb -font "JetBrainsMonoNerdFontMono:size=10"'

