#!/bin/sh
cd ~
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export QT_SCALE_FACTOR=1
export GBM_BACKEND=nvidia-drm
export LIBVA_DRIVER_NAME=nvidia
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland 
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=wlr
export XDG_SESSION_DESKTOP=wlr
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
#FOR VM TESTING ONLY vvv
#export WLR_RENDERER_ALLOW_SOFTWARE=1

export BEMENU_OPTS="
    --ignorecase\
    --prompt ''\
    --fn 'Terminus 10'\
    --ch '20'\
    --center\
    --width-factor '0.25'\
    --list '14'\
    --line-height '26'\
    --fixed-height\
    --border '2'\
    --bdr '#ebdbb2'\
    --hb '#504945' --hf '#ebdbb2'\
    --nb '#282828' --nf '#d5c4a1'\
    --ab '#282828' --af '#d5c4a1'\
    --fb '#282828' --ff '#d5c4a1'\
"

someblocks -p | dwlb -status-stdin all &
exec dbus-launch --exit-with-session dwl -s 'dwlb'

